### PR TITLE
deploy: Make .AppImage executable by default

### PR DESCRIPTION
**Pull request by patrickelectric**
Solves #96

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by jaxxzer** [comment]
Hm, it doesn't work for either S3 or github releases. I have not been able to find any definitive information as to why. It looks like linux permissions don't apply to S3.

**Comment by patrickelectric** [comment]
:disappointed: I'll take a look on this.

**Comment by patrickelectric** [comment]
@jaxxzer can you test this approach ?

**Comment by jaxxzer** [comment]
I tried something else this morning: https://github.com/bluerobotics/qgroundcontrol/tree/patrickelectric-app

It looks like permissions are correct on travis: https://travis-ci.org/bluerobotics/qgroundcontrol/jobs/290545568#L3051

Something is happening after this step.

**Comment by patrickelectric** [comment]
Making .AppImage executable by default can break desktop integration.
Refs:
- electron-userland/electron-builder#1353
- [common-mistake](https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake)

We can close this issue.

**Comment by jaxxzer** [comment]
Thanks Patrick.

**Pull request closed without merging**
